ETISS 0.8.0: /home/runner/work/etiss/etiss/src/SimpleMemSystem.cpp File Reference
SimpleMemSystem.cpp File Reference
implementation of etiss/SimpleMemSystem.h
#include "etiss/SimpleMemSystem.h"
#include "etiss/CPUArch.h"
#include "etiss/Misc.h"
#include <cstring>
#include <iostream>
#include <fstream>
#include <unordered_map>
#include "elfio/elfio.hpp"
#include <memory>
Macros
#define ARMv6M_DEBUG_PRINT 0
#define MAX_MEMSEGS 99
Functions
uint32_t printMessage (std::string key, std::string message, uint32_t maxCount)
void access_error (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len, std::string error, etiss::Verbosity verbosity)
static void trace (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len, bool isWrite, bool toFile, std::ofstream &file)
void global_sync_time (uint64 time_ps)
Variables
std::unordered_map< std::string, uint32_t > map_messageCounter
Detailed Description
implementation of etiss/SimpleMemSystem.h
Copyright
Copyright 2018 Infineon Technologies AG
This file is part of ETISS tool, see https://github.com/tum-ei-eda/etiss.
The initial version of this software has been created with the funding support by the German Federal
Ministry of Education and Research (BMBF) in the project EffektiV under grant 01IS13022.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and
the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Author
Marc Greim marc..nosp@m.grei.nosp@m.m@myt.nosp@m.um.d.nosp@m.e, Chair of Electronic Design Automation, TUM
Date
July 29, 2014
Version
0.1
Definition in file SimpleMemSystem.cpp.
Macro Definition Documentation
ARMv6M_DEBUG_PRINT
#define ARMv6M_DEBUG_PRINT 0
Definition at line 64 of file SimpleMemSystem.cpp.
MAX_MEMSEGS
#define MAX_MEMSEGS 99
Definition at line 65 of file SimpleMemSystem.cpp.
Function Documentation
access_error()
void access_error (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len, std::string error, etiss::Verbosity verbosity)
Definition at line 293 of file SimpleMemSystem.cpp.
References ETISS_CPU::instructionPointer, etiss::log(), and etiss::verbosity().
Referenced by etiss::SimpleMemSystem::dbus_access(), etiss::SimpleMemSystem::iread(), and etiss::SimpleMemSystem::iwrite().
global_sync_time()
void global_sync_time (uint64 time_ps)
printMessage()
uint32_t printMessage (std::string key, std::string message, uint32_t maxCount)
Definition at line 70 of file SimpleMemSystem.cpp.
References map_messageCounter, and uint32_t.
trace()
static void trace (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len, bool isWrite, bool toFile, std::ofstream & file) static
Definition at line 318 of file SimpleMemSystem.cpp.
References ETISS_CPU::cpuTime_ps.
Referenced by etiss::SimpleMemSystem::dbus_access().
Variable Documentation
map_messageCounter
std::unordered_map<std::string, uint32_t> map_messageCounter
Definition at line 69 of file SimpleMemSystem.cpp.
Referenced by printMessage().