ETISS 0.8.0: utf32_counter Struct Reference
utf32_counter Struct Reference
Public Types
typedef size_t value_type
Static Public Member Functions
static value_type low (value_type result, uint32_t)
static value_type high (value_type result, uint32_t)
Detailed Description
Definition at line 851 of file pugixml.cpp.
Member Typedef Documentation
value_type
typedef size_t utf32_counter::value_type
Definition at line 853 of file pugixml.cpp.
Member Function Documentation
high()
static value_type utf32_counter::high (value_type result, uint32_t) inline static
Definition at line 857 of file pugixml.cpp.
Referenced by get_metrics.MemRange::stats(), get_metrics.MemRange::trace(), and get_metrics.MemRange::usage().
low()
static value_type utf32_counter::low (value_type result, uint32_t) inline static
Definition at line 855 of file pugixml.cpp.
Referenced by get_metrics.MemRange::stats(), get_metrics.MemRange::trace(), and get_metrics.MemRange::usage().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp