ETISS 0.8.0: etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem Struct Reference
etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem Struct Reference
Public Attributes
struct ETISS_System sys
MemoryDeviceMapper * this_
ETISS_System * orig
bool(* fastrule)(uint64_t addr, unsigned len)
Detailed Description
Definition at line 53 of file MemoryDevice.cpp.
Member Data Documentation
fastrule
bool(* etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::fastrule) (uint64_t addr, unsigned len)
Definition at line 62 of file MemoryDevice.cpp.
Referenced by etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_read_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_write_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dread_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dwrite_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iread_(), and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iwrite_().
orig
ETISS_System* etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::orig
Definition at line 60 of file MemoryDevice.cpp.
Referenced by etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_read_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_write_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dread_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dwrite_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iread_(), and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iwrite_().
sys
struct ETISS_System etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::sys
Definition at line 134 of file MemoryDevice.cpp.
this_
MemoryDeviceMapper* etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::MapperSystem::this_
Definition at line 58 of file MemoryDevice.cpp.
Referenced by etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_read_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dbg_write_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dread_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::dwrite_(), etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iread_(), and etiss::plugin::anonymous_namespace{MemoryDevice.cpp}::iwrite_().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/IntegratedLibrary/MemoryDevice.cpp