ETISS 0.8.0: utf8_writer Struct Reference
utf8_writer Struct Reference
Public Types
typedef uint8_t * value_type
Static Public Member Functions
static value_type low (value_type result, uint32_t ch)
static value_type high (value_type result, uint32_t ch)
static value_type any (value_type result, uint32_t ch)
Detailed Description
Definition at line 769 of file pugixml.cpp.
Member Typedef Documentation
value_type
typedef uint8_t* utf8_writer::value_type
Definition at line 771 of file pugixml.cpp.
Member Function Documentation
any()
static value_type utf8_writer::any (value_type result, uint32_t ch) inline static
Definition at line 808 of file pugixml.cpp.
References high(), and low().
Referenced by strconv_escape().
high()
static value_type utf8_writer::high (value_type result, uint32_t ch) inline static
Definition at line 798 of file pugixml.cpp.
References uint8_t.
Referenced by any(), get_metrics.MemRange::stats(), get_metrics.MemRange::trace(), and get_metrics.MemRange::usage().
low()
static value_type utf8_writer::low (value_type result, uint32_t ch) inline static
Definition at line 773 of file pugixml.cpp.
References uint8_t.
Referenced by any(), get_metrics.MemRange::stats(), get_metrics.MemRange::trace(), and get_metrics.MemRange::usage().
The documentation for this struct was generated from the following file:
/home/runner/work/etiss/etiss/src/fault/xml/pugixml.cpp